# Site settings
title: "Digital Publication in Mediterranean Archaeology"
subtitle: "Current Practice and Common Goals"

author: "Institute for the Study of the Ancient World"
description: "TK"
keywords: ""
biography: "TK."
colophon: "Designed by <a href="http://diyclassics.github.io">Patrick J. Burns</a> | Theme by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: "/dpma"
#url: ""

twitter_username: 
github_username: 
linkedin_username: 
facebook_username: 
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
